Simulate build failure

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -51,6 +51,10 @@ jobs:
           name: dist
           path: dist
 
+      #! Temporary failure simulation to test failure job
+      - name: Simulate Build Failure
+        run: exit 1
+
       - name: Run Build to Check for Errors
         run: |
           npm start & sleep 2
@@ -130,12 +134,12 @@ jobs:
       #         --zip-file fileb://upload.zip
       #     fi
 
-      # - name: Deploy to Lambda
-      #   id: deploy-to-lambda
-      #   run: |
-      #     aws lambda update-function-code \
-      #       --function-name davidscript-server \
-      #       --zip-file fileb://upload.zip
+      - name: Deploy to Lambda
+        id: deploy-to-lambda
+        run: |
+          aws lambda update-function-code \
+            --function-name davidscript-server \
+            --zip-file fileb://upload.zip
 
   #--------------------------------------------------------------------------
   #
@@ -168,9 +172,9 @@ jobs:
 
   failure:
     name: Deploy Failure
-    needs: [build, deploy]
-    # Run when ANY job in Deploy workflow produces failure.
-    if: failure()
+    needs: deploy
+    # Run when ANY job in Deploy workflow produces failure, but wait on build & deploy.
+    if: failure() || needs.build.result == 'failure'
     runs-on: ubuntu-latest
     steps:
       - name: Log Failure
