Simulate deploy job failure

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -51,9 +51,8 @@ jobs:
           name: dist
           path: dist
 
-      #! Temporary failure simulation to test failure job
-      - name: Simulate Build Failure
-        run: exit 1
+      # - name: Simulate Build Failure
+      #   run: exit 1
 
       - name: Run Build to Check for Errors
         run: |
@@ -95,6 +94,10 @@ jobs:
         # This assumes bestzip is in package.json dependencies.
         run: npx bestzip upload.zip dist/* package.json
 
+      #! Temporary failure simulation to test failure job
+      - name: Simulate Deploy Failure
+        run: exit 1
+
       - name: Configure AWS credentials
         # https://github.com/aws-actions/configure-aws-credentials
         uses: aws-actions/configure-aws-credentials@v4
@@ -107,32 +110,6 @@ jobs:
       # need to install any additional tools for the aws lambda command to work in your GitHub workflow.
       # Note: the Lambda function would not be created automatically if it didn't exist, you would encounter an error.
       # To create a new Lambda function, you would need to use the aws lambda create-function command.
-      #
-      # If you wanted to run logic to creat or update it would look something like this, but this is still just example code:
-      #
-      # - name: Check if Lambda Function Exists
-      #   id: check-lambda
-      #   run: |
-      #     aws lambda get-function --function-name davidscript-server || echo "NOT_FOUND"
-
-      # - name: Create or Update Lambda Function
-      #   run: |
-      #     if [ "${{ steps.check-lambda.outputs.stdout }}" == "NOT_FOUND" ]; then
-      #       echo "Creating Lambda function"
-      #       aws lambda create-function \
-      #         --function-name davidscript-server \
-      #         --runtime nodejs22.x \
-      #         --role arn:aws:iam::account-id:role/execution_role \
-      #         --handler index.handler \
-      #         --zip-file fileb://upload.zip \
-      #         --description "My Lambda function for deploying server" \
-      #         --timeout 15 \
-      #     else
-      #       echo "Updating Lambda function"
-      #       aws lambda update-function-code \
-      #         --function-name davidscript-server \
-      #         --zip-file fileb://upload.zip
-      #     fi
 
       # - name: Deploy to Lambda
       #   id: deploy-to-lambda
